

USE MOVIE_ANALYSIS

GO

SELECT *
FROM MOVIE_ANALYSIS.DBO.movies_initial
ORDER BY 2,3

--column names

SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'movies_initial';

--Find the highest-rated movies in each genre.


WITH HIGHEST_RATED_MOVIES 
AS
(
SELECT TITLE, YEAR, RELEASED, DIRECTOR, GENRE, IMDBRATING, 
ROW_NUMBER() OVER (PARTITION BY  GENRE ORDER BY IMDBRATING DESC) AS Rank
FROM MOVIE_ANALYSIS.DBO.movies_initial
)
select *
from HIGHEST_RATED_MOVIES
WHERE Rank = 1
order by imdbrating desc



--Identify directors with the most highly-rated films.

WITH HIGHLY_RATED_FILMS

AS

(
SELECT TITLE, DIRECTOR, YEAR, RANK() OVER (PARTITION BY GENRE ORDER BY IMDBRATING DESC) AS RANK
FROM MOVIE_ANALYSIS.DBO.movies_initial
WHERE DIRECTOR IS NOT NULL
)
SELECT DIRECTOR, COUNT(*) AS NUMBEROFMOVIES
FROM HIGHLY_RATED_FILMS
WHERE RANK <=10
GROUP BY DIRECTOR



--Analyze trends in movie ratings over time.
SELECT YEAR(YEAR) AS YEAR, AVG(IMDBRATING) AS AVGIMDBRATING
FROM MOVIE_ANALYSIS.DBO.movies_initial
WHERE YEAR IS NOT NULL
GROUP BY YEAR
ORDER BY YEAR 

--Check the most frequent actors in hit movies

SELECT CAST AS ACTOR, COUNT(*) AS NUMBEROFMOVIES 
FROM MOVIE_ANALYSIS.DBO.movies_initial
WHERE IMDBRATING >= 8 AND CAST IS NOT NULL
GROUP BY CAST
HAVING COUNT(*) > 2
ORDER BY NUMBEROFMOVIES DESC


--GROUPING MOVIES ACCORDING TO LANGUAGES

SELECT [LANGUAGE] AS MOVIELANGUAGE, COUNTRY, COUNT(*) AS NUMBEROFMOVIES
FROM MOVIE_ANALYSIS.DBO.movies_initial
WHERE LANGUAGE IS NOT NULL
GROUP BY [LANGUAGE], COUNTRY
ORDER BY NUMBEROFMOVIES DESC

--GROUPING MOVIES ACCORDING TO GENRE
SELECT GENRE, COUNT(*) AS NUMBEROFMOVIES
FROM MOVIE_ANALYSIS.DBO.movies_initial
WHERE TITLE IS NOT NULL AND GENRE IS NOT NULL
GROUP BY GENRE
ORDER BY NUMBEROFMOVIES DESC


--HIGHEST AWARD WINNING MOVIES

SELECT TITLE, awards
FROM MOVIE_ANALYSIS.DBO.movies_initial
WHERE TITLE IS NOT NULL AND awards IS NOT NULL 
AND AWARDS LIKE '%w%'
GROUP BY awards, TITLE
ORDER BY AWARDS DESC

--oscar winning movies
SELECT TITLE, awards
FROM MOVIE_ANALYSIS.DBO.movies_initial
WHERE TITLE IS NOT NULL AND awards IS NOT NULL 
AND AWARDS LIKE '%oscar%' and awards not like '%nominated%'
GROUP BY awards, TITLE
ORDER BY AWARDS DESC

--total ACTION movies
SELECT GENRE,COUNT(TITLE) AS TOTAL_ACTION_MOVIES
FROM MOVIE_ANALYSIS.DBO.movies_initial
WHERE TITLE IS NOT NULL 
AND GENRE LIKE '%ACTION%'
GROUP BY GENRE
ORDER BY TOTAL_ACTION_MOVIES DESC


--temp table
DROP table if exists #genre
create table #genre
(

Title  nvarchar(500),
Year nvarchar(10),
Genre nvarchar(255),
Released nvarchar(10),
Country nvarchar(255)
)
INSERT INTO #genre  
SELECT title, year, genre, released, country
FROM MOVIE_ANALYSIS.DBO.movies_initial
WHERE title IS NOT NULL AND genre IS NOT NULL;

select *
from #genre


--Creating View to store data for later visualizations

create view genre as 

select title, year, genre, released, country
FROM MOVIE_ANALYSIS.DBO.movies_initial
WHERE title IS NOT NULL AND genre IS NOT NULL

select *
from genre